general.import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true
padding = { x = 5, y = 5 }

[font]
size = 12
bold = { family = "CaskaydiaCove Nerd Font Mono", style = "Bold"}
italic = { family = "CaskaydiaCove Nerd Font Mono", style = "Italic"}
normal = { family = "CaskaydiaCove Nerd Font Mono", style = "Regular"}
bold_italic = { family = "CaskaydiaCove Nerd Font Mono", style = "Bold Italic"}
