general.import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
# blur = true
# opacity = 0.9
padding = { x = 5, y = 5 }

[font]
size = 12
normal = { family = "CaskaydiaCove Nerd Font Mono", style = "Regular" }
