WHEEL_UP add volume 2
WHEEL_DOWN add volume -2
UP    add volume 2
DOWN  add volume -2
AXIS_UP add volume 2
AXIS_DOWN add volume -2
Ctrl+RIGHT seek 85 exact
Ctrl+LEFT seek -85 exact
Shift+RIGHT frame-step
Shift+LEFT frame-back-step
H seek -65
h seek 65
v cycle deband
a cycle audio
s cycle sub
i cycle interpolation
- add video-zoom -.25
+ add video-zoom .25
